/**
 * `npm run gen:api`: TypeScript types from the API's OpenAPI schema.
 *
 * Input, in order of preference:
 *   1. apps/web/openapi.json, written by the backend's scripts/gen-openapi.sh
 *      (the live schema of the API being built);
 *   2. apps/web/openapi.snapshot.json, the checked-in snapshot used until (1)
 *      exists. It was produced read-only from the FastAPI app itself:
 *        python -c "from fiboki.api.app import create_app; \
 *                   import json; print(json.dumps(create_app().openapi()))"
 *      so it describes the routers as they are, not as anyone remembers them.
 *
 * Output: lib/generated/openapi.ts (committed). tests/e2e/source-rules.spec.ts
 * fails if it is not what this script would write from the current input, so
 * a schema change cannot land without its types.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
export const WEB_ROOT = join(HERE, "..");
export const OUTPUT = join(WEB_ROOT, "lib", "generated", "openapi.ts");

export function schemaInput() {
  const live = join(WEB_ROOT, "openapi.json");
  return existsSync(live) ? live : join(WEB_ROOT, "openapi.snapshot.json");
}

export async function generate() {
  const { default: openapiTS, astToString } = await import("openapi-typescript");
  const input = schemaInput();
  const ast = await openapiTS(pathToFileURL(input), { alphabetize: true });
  const header =
    "/**\n" +
    ` * GENERATED by \`npm run gen:api\` from ${basename(input)}. Do not edit by hand.\n` +
    " * Hand-written contracts that stay authoritative locally (Figure, SourceNote,\n" +
    " * Provenance) live in lib/types.ts; see scripts/gen-api.mjs.\n" +
    " */\n\n";
  return header + astToString(ast);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = await generate();
  const changed = !existsSync(OUTPUT) || readFileSync(OUTPUT, "utf8") !== text;
  writeFileSync(OUTPUT, text);
  console.log(`${changed ? "wrote" : "unchanged"} ${OUTPUT} from ${basename(schemaInput())}`);
}
