"""Fiboki V2 market-state and regime engine.

Four layers, each usable on its own:

``features``     causal per-instrument feature engine, every feature warmup-declared
``cross_asset``  windowed correlation, currency strength, risk appetite, lead-lag
``regime``       multidimensional regime vector, transitions, trade segmentation
``calendar``     economic-event interface + file-backed implementation (no network)
``state_engine`` the continuous engine that ties them together and persists history

The contract the whole package rests on: **no value published at bar i depends
on any bar after i**, and **no statistic is computed against the full sample**.
Both are enforced by tests, not by convention.
"""
from fiboki.marketstate.calendar import (
    USER_ACTION_NOTE,
    BlackoutWindow,
    CalendarCoverage,
    CalendarError,
    EconomicCalendar,
    EconomicEvent,
    ImpactLevel,
    InMemoryEconomicCalendar,
    RecurringEventType,
    instrument_currencies,
    load_events_csv,
    load_events_json,
    load_recurring_event_types,
    recurring_types_for,
    synthesise_events,
)
from fiboki.marketstate.cross_asset import (
    AlignedPanel,
    CoverageReport,
    CrossAssetError,
    CrossAssetState,
    CurrencyStrength,
    InstrumentCoverage,
    LeadLag,
    RiskAppetite,
    RiskProxyConfig,
    RollingCorrelation,
    align_panel,
    build_cross_asset_state,
    correlation_breakdown,
    currency_strength,
    lead_lag,
    risk_appetite,
    rolling_correlation,
)
from fiboki.marketstate.features import (
    FEATURE_ENGINE_VERSION,
    DroppedBars,
    FeatureConfig,
    FeatureEngine,
    FeatureError,
    FeatureSet,
    FeatureSpec,
    InvalidBarError,
    assert_features_causal,
    corrupt_future,
    corwin_schultz_spread,
    drop_invalid_bars,
    expanding_rank_pct,
    hurst_from_variance_ratio,
    invalid_bar_mask,
    naive_expanding_rank_pct,
    rolling_ols_stats,
    session_flags,
    variance_ratio,
)
from fiboki.marketstate.regime import (
    REGIME_VERSION,
    DirectionAxis,
    LiquidityAxis,
    PersistenceAxis,
    RegimeAxis,
    RegimeClassifier,
    RegimeConfig,
    RegimeDependence,
    RegimeError,
    RegimeSeries,
    RegimeThresholds,
    RegimeVector,
    StressAxis,
    VolatilityAxis,
    confirm,
    describe_regimes,
    regime_dependence,
    regime_segmented_performance,
)
from fiboki.marketstate.state_engine import (
    STATE_ENGINE_VERSION,
    EngineConfig,
    MarketStateEngine,
    MarketStateSnapshot,
    StateEngineError,
    build_engine,
)

__all__ = [
    "FEATURE_ENGINE_VERSION",
    "REGIME_VERSION",
    "STATE_ENGINE_VERSION",
    "USER_ACTION_NOTE",
    "AlignedPanel",
    "BlackoutWindow",
    "CalendarCoverage",
    "CalendarError",
    "CoverageReport",
    "CrossAssetError",
    "CrossAssetState",
    "CurrencyStrength",
    "DirectionAxis",
    "DroppedBars",
    "EconomicCalendar",
    "EconomicEvent",
    "EngineConfig",
    "FeatureConfig",
    "FeatureEngine",
    "FeatureError",
    "FeatureSet",
    "FeatureSpec",
    "ImpactLevel",
    "InMemoryEconomicCalendar",
    "InstrumentCoverage",
    "InvalidBarError",
    "LeadLag",
    "LiquidityAxis",
    "MarketStateEngine",
    "MarketStateSnapshot",
    "PersistenceAxis",
    "RecurringEventType",
    "RegimeAxis",
    "RegimeClassifier",
    "RegimeConfig",
    "RegimeDependence",
    "RegimeError",
    "RegimeSeries",
    "RegimeThresholds",
    "RegimeVector",
    "RiskAppetite",
    "RiskProxyConfig",
    "RollingCorrelation",
    "StateEngineError",
    "StressAxis",
    "VolatilityAxis",
    "align_panel",
    "assert_features_causal",
    "build_cross_asset_state",
    "build_engine",
    "confirm",
    "correlation_breakdown",
    "corrupt_future",
    "corwin_schultz_spread",
    "currency_strength",
    "describe_regimes",
    "drop_invalid_bars",
    "expanding_rank_pct",
    "hurst_from_variance_ratio",
    "instrument_currencies",
    "invalid_bar_mask",
    "lead_lag",
    "load_events_csv",
    "load_events_json",
    "load_recurring_event_types",
    "naive_expanding_rank_pct",
    "recurring_types_for",
    "regime_dependence",
    "regime_segmented_performance",
    "risk_appetite",
    "rolling_correlation",
    "rolling_ols_stats",
    "session_flags",
    "synthesise_events",
    "variance_ratio",
]
