"""Signal model for strategy outputs."""

from datetime import datetime

from pydantic import BaseModel, Field

from fibokei.core.models import Direction, Timeframe


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    timestamp: datetime
    instrument: str
    timeframe: Timeframe
    strategy_id: str
    direction: Direction
    setup_type: str
    entry_type: str = "market"  # market, limit, stop
    proposed_entry: float
    stop_loss: float
    take_profit_primary: float
    take_profit_secondary: float | None = None
    confidence_score: float = Field(ge=0.0, le=1.0)
    regime_label: str = "unknown"
    signal_valid: bool = True
    invalidation_reason: str | None = None
    rationale_summary: str = ""
    supporting_factors: list[str] = Field(default_factory=list)
    annotation_payload: dict | None = None
